---
- hosts: localhost
  become: yes
  connection: local
  roles:
    - create-instance

- hosts: build
  become: yes
  remote_user: ubuntu
  roles:
    - aws-build

- hosts: prod
  become: yes
  remote_user: ubuntu
  roles:
    - aws-prod