---
- hosts: localhost
  become: yes
  connection: local
  roles:
    - create_instance

- hosts: build
  become: yes
  remote_user: ubuntu
  roles:
    - aws_build

- hosts: prod
  become: yes
  remote_user: ubuntu
  roles:
    - aws_prod

- hosts: localhost
  become: yes
  connection: local
  roles:
    - terminate_build_instance